# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 06:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='栏目名称')),
                ('en_name', models.CharField(max_length=50, verbose_name='栏目英文名称')),
                ('index', models.IntegerField(default=100, verbose_name='顺序')),
                ('display', models.CharField(choices=[('0', '隐藏'), ('1', '显示')], default='1', max_length=1, verbose_name='是否显示')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='新增时间')),
            ],
            options={
                'verbose_name': '新闻栏目',
                'verbose_name_plural': '新闻栏目',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='新闻标题')),
                ('en_title', models.CharField(max_length=100, verbose_name='英文新闻标题')),
                ('surface_plot', models.ImageField(upload_to='news/%Y/%m', verbose_name='封面图')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('summary', models.CharField(default='', max_length=500, verbose_name='新闻概要')),
                ('en_summary', models.CharField(default='', max_length=500, verbose_name='英文新闻概要')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('en_content', models.TextField(default='', verbose_name='英文内容')),
                ('display', models.CharField(choices=[('0', '隐藏'), ('1', '显示')], default='1', max_length=1, verbose_name='是否显示')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Category', verbose_name='栏目')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
            },
        ),
    ]
