# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 08:33
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='news',
            name='en_content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='英文内容'),
        ),
        migrations.AlterField(
            model_name='news',
            name='en_summary',
            field=models.TextField(default='', verbose_name='英文新闻概要'),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.TextField(default='', verbose_name='新闻概要'),
        ),
    ]
