# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='企业名称')),
                ('en_name', models.CharField(max_length=100, verbose_name='英文企业名称')),
                ('logo', models.ImageField(upload_to='companyinfo/%Y/%m', verbose_name='企业logo')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('en_address', models.CharField(max_length=200, verbose_name='英文地址')),
                ('tel', models.CharField(max_length=50, verbose_name='联系电话')),
                ('db_email', models.EmailField(max_length=100, verbose_name='企业合作邮箱')),
                ('market_email', models.EmailField(max_length=100, verbose_name='市场推广合作邮箱')),
                ('hr_email', models.EmailField(max_length=100, verbose_name='人事邮箱')),
                ('summary', models.TextField(verbose_name='企业介绍')),
                ('en_summary', models.TextField(verbose_name='英文企业介绍')),
                ('core_business', models.TextField(verbose_name='核心业务')),
                ('en_core_business', models.TextField(verbose_name='英文核心业务')),
            ],
            options={
                'verbose_name': '企业信息',
                'verbose_name_plural': '企业信息',
            },
        ),
    ]
