# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='db_email',
            new_name='bd_email',
        ),
    ]
