# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 08:33
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20180108_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='core_business',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='核心业务'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='en_core_business',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='英文核心业务'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='en_summary',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='英文企业介绍'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='summary',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='企业介绍'),
        ),
    ]
