# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 05:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180108_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnMoreService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='区块标题')),
                ('en_title', models.CharField(max_length=100, verbose_name='区块英文标题')),
                ('icon', models.ImageField(upload_to='learn/%Y/%m', verbose_name='图标')),
                ('summary', models.CharField(max_length=500, verbose_name='描述')),
                ('en_summary', models.CharField(max_length=500, verbose_name='英文描述')),
                ('index', models.IntegerField(blank=True, default=100, verbose_name='顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='上传时间')),
            ],
            options={
                'verbose_name_plural': '优势与服务',
                'verbose_name': '优势与服务',
            },
        ),
        migrations.AlterField(
            model_name='banner',
            name='index',
            field=models.IntegerField(blank=True, default=100, verbose_name='顺序'),
        ),
    ]
