# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 05:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180108_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='伙伴名称')),
                ('en_name', models.CharField(max_length=50, verbose_name='伙伴英文名称')),
                ('image', models.ImageField(upload_to='partner/%Y/%m', verbose_name='图片')),
                ('index', models.IntegerField(blank=True, default=100, verbose_name='顺序')),
                ('display', models.CharField(choices=[('0', '隐藏'), ('1', '显示')], default='1', max_length=1, verbose_name='是否显示')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='上传时间')),
            ],
            options={
                'verbose_name_plural': '合作伙伴',
                'verbose_name': '合作伙伴',
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='display',
            field=models.CharField(choices=[('0', '隐藏'), ('1', '显示')], default='1', max_length=1, verbose_name='是否显示'),
        ),
        migrations.AddField(
            model_name='learnmoreservice',
            name='display',
            field=models.CharField(choices=[('0', '隐藏'), ('1', '显示')], default='1', max_length=1, verbose_name='是否显示'),
        ),
    ]
