# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 07:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=50, verbose_name='岗位名称')),
                ('en_job_name', models.CharField(max_length=50, verbose_name='英文岗位名称')),
                ('job_nums', models.IntegerField(default=1, verbose_name='招聘数量')),
                ('job_desc', models.TextField(verbose_name='岗位职责')),
                ('en_job_desc', models.TextField(verbose_name='英文岗位职责')),
                ('requirements', models.TextField(verbose_name='任职要求')),
                ('en_requirements', models.TextField(verbose_name='英文任职要求')),
                ('index', models.IntegerField(default=100, verbose_name='顺序')),
                ('display', models.CharField(choices=[('0', '隐藏'), ('1', '显示')], default='1', max_length=1, verbose_name='是否显示')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '招聘岗位',
                'verbose_name_plural': '招聘岗位',
            },
        ),
    ]
