# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 08:33
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='en_job_desc',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='英文岗位职责'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='en_requirements',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='英文任职要求'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='job_desc',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='岗位职责'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='requirements',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='任职要求'),
        ),
    ]
